title: Vibrato Notes
short-description: An Innovative, Secure, and Open-source Note-taking Application

navigation:
  - text: Features
    url: "#feature"
  - text: Screenshots
    url: "#screenshot"
  - text: Pricing
    url: "#pricing"
  - text: Download
    url: "#download"
  - text: Contact
    url: "#contact"
